server {
    listen 80;

    root /usr/share/nginx/html;

    index home.html;

    location / {
        try_files $uri $uri/ /home.html;
    }

    location /home {
        try_files /home.html =404;
    }

    location /cart {
        try_files /cart.html =404;
    }

    location /admin {
        try_files /admin.html =404;
    }
}